Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.box_url = "https://vagrantcloud.com/ubuntu/boxes/focal64"

  config.vm.define "kmoutaouS" do |server|
    server.vm.hostname = "kmoutaouS"

    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "virtualbox" do |vb|
      vb.name = "kmoutaouS"
      vb.memory = 1024
      vb.cpus = 1
    end

    server.vm.synced_folder "./apps", "/home/vagrant/apps"

    server.vm.provision "shell", path: "scripts/install-k3s-server.sh"
  end
end
