all: init

init:
	@echo "Building the project..."
	@./scripts/init.sh

clean:
	@echo "Cleaning the project..."
	@./scripts/clean.sh

gitlab:
	@echo "Installing gitlab..."
	@./scripts/install.sh

deploy:
	@echo "Deploying the application..."
	@./scripts/createApp.sh

info:
	@echo "Project information..."
	@./scripts/getInfo.sh
