all: init

init:
	@echo "Building the project..."
	@./scripts/init.sh

clean:
	@echo "Cleaning the project..."
	@./scripts/clean.sh

install:
	@echo "Installing the project..."
	@./scripts/install.sh

info:
	@echo "Project information..."
	@./scripts/getInfo.sh
